//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<long> Phone_Number { get; set; }
        public string Email { get; set; }
        public Nullable<int> Debt_Id { get; set; }
        public string Location { get; set; }
        public bool Type { get; set; }


       
    }

   
}
