//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class productsAllnfo
    {
        public long SKU { get; set; }
        public string اسم_المنتج { get; set; }
        public double الكمية { get; set; }
        public decimal سعر_الشراء { get; set; }
        public decimal سعر_البيع { get; set; }
        public string الوحده { get; set; }
        public string الصنف { get; set; }
        public string المكان { get; set; }
        public string المخزن { get; set; }
        public int رقم_الفاتورة { get; set; }
    }
}
